apiVersion: v1
kind: Service
metadata:
  name: frm-service
  namespace: frm-staging
spec:
  selector:
    app.kubernetes.io/name: MyApp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376