apiVersion: configsync.gke.io/v1alpha1
kind: RepoSync
metadata:
  name: repo-sync-frm-testing
  namespace: frm-testing
spec:
  sourceFormat: unstructured
  git:
    # If you fork this repo, change the url to point to your fork
    repo: https://github.com/sushmatn25/guardian-config-sync-test.git
    # If you move the configs to a different branch, update the branch here
    branch: main
    dir: namespaces/frm-testing
    # We recommend securing your source repository.
    # Other supported auth: `ssh`, `cookiefile`, `token`, `gcenode`.
    auth: none
    # Refer to a Secret you create to hold the private key, cookiefile, or token.
    # secretRef:
    #   name: SECRET_NAME
# [END anthosconfig_config_sync_quickstart_multirepo_root_repo_sync] 