apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: frm-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: frm-testing
- kind: ServiceAccount
  name: ns-reconciler-frm-testing-repo-sync-frm-testing-21
  namespace: config-management-system