kind: RoleBinding
apiVersion: net.gke.io/v1
metadata:
  name: frm-testing-admin-net
subjects:
- kind: ServiceAccount
  name: ns-reconciler-frm-testing-repo-sync-frm-testing-21
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: net.gke.io