kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: frm-testing-admin
  namespace: frm-testing
subjects:
- kind: ServiceAccount
  name: ns-reconciler-frm-testing-repo-sync-frm-testing-21
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io