apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: urm-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: urm-testing
- kind: ServiceAccount
  name: ns-reconciler-urm-testing-repo-sync-urm-testing-21
  namespace: config-management-system